### ISSUE TITLE
What is it mean?

### ISSUE THREAD

**Issue by smmweddjxing** [Gota7/Miyamoto#125]
--------------------------------------------------------------------------------
2023-12-03, 16:06:43
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "miyamoto.py", line 5659, in <module>
  File "miyamoto.py", line 5649, in main
  File "miyamoto.py", line 305, in __init2__
  File "miyamoto.py", line 3158, in HandleRotationPreview
AttributeError: 'NoneType' object has no attribute 'sprites'

**Comment by aboood40091** [comment]
Which version of Miyamoto were you using?

**Comment by smmweddjxing** [comment]
29(No DX)

**Comment by aboood40091** [comment]
Could you give me a bit more context? What were you doing before the error happened? Did it only happen once or can you get it to trigger consistently?
